### ISSUE TITLE
-P flag appears to be broken in example README command

### ISSUE THREAD

**Issue by jharlow-intel** [IntelPython/fft_benchmark#18]
Summary:

It seems as though the `-P` flag and it's other synonyms break the `fft_bench.py` script for a particular command given in the README
` python fft_bench.py -P -r -t 1 -d float32 -o 5 100000000`

Output:
```
(fft-bench) harlowjo@harlowjo-mobl:~/repositories/IntelPython/fft_benchmark$ python fft_bench.py -P -r -t 1 -d float32 -o 5 100000000
/home/harlowjo/miniconda3/envs/fft-bench/lib/python3.10/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.5
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"
TAG: CONDA_DEFAULT_ENV = fft-bench
TAG: numpy.__mkl_version__ = 2023.0.1

prefix,module,function,threads,dtype,size,place,time
Traceback (most recent call last):
  File "/home/harlowjo/repositories/IntelPython/fft_benchmark/fft_bench.py", line 169, in <module>
    perf_times = perf.time_func(func, arr, kwargs, **time_kwargs)
  File "/home/harlowjo/repositories/IntelPython/fft_benchmark/perf.py", line 161, in time_func
    res = func(buf, **kwargs)
  File "/home/harlowjo/miniconda3/envs/fft-bench/lib/python3.10/site-packages/mkl_fft/_scipy_fft_backend.py", line 113, in __ua_function__
    return fn(*args, **kwargs)
TypeError: rfft() got an unexpected keyword argument 'overwrite_x'
```

Steps to reproduce:

I followed the README instructions nearly identically

1) `conda create -n fft-bench -c intel numpy scipy`
2) `conda activate fft-bench`
3)  `python fft_bench.py -P -r -t 1 -d float32 -o 5 100000000`

I noticed I can run the same command without `-P` and it works. 
Running it with `--overwrite-x` and `--in-place` caused the same error as above.

Please let me know if I did something wrong with my setup or if you need more info

**Comment by oleksandr-pavlyk** [comment]
The `rfft` does not provide in-place operation mode. Please do not use `-P` when compute FFT of real-value floating-point type datasets.
